### ISSUE TITLE
Content of `NumberInput` Not Scrollable on Safari

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#83] opened 2024-07-07 12:40 UTC
### Describe the bug

The `NumberInput` component is not scrollable when the content exceeds the visible area on Safari. This issue prevents users from being able to view or edit the full content.

### Expected Behavior
The `NumberInput` should be scrollable, allowing users to view and edit all content.

### Actual Behavior
The `NumberInput` is not scrollable, and the overflow content is not accessible.

### Steps to Reproduce

1. Open Safari.
2. Navigate to the page containing the `NumberInput` component.
3. Enter content that exceeds the visible area of the `NumberInput`.

### Operating System

MacOS

### What browsers are you seeing the problem on?

Safari

### What device are you using?

Desktop, Mobile

### Related Issues:

#81 #82

**Comment by mad-moo** [comment] 2024-07-07 21:08
Duplicate of #82, since number inputs are just text inputs

**Closed by mad-moo** 2024-07-07 21:08 UTC
Labels: bug, layouting rework branch
