### ISSUE TITLE
[Feature Request] App Window: standardize on pywebview[qt]

### ISSUE THREAD

**Issue by iwr-redmond** [rio-labs/rio#164] opened 2024-11-13 19:48 UTC
### Description

This request involves the window icon for local app mode.

According to the [pyproject.toml](https://github.com/rio-labs/rio/blob/main/pyproject.toml), pywebview 4.2 is installed on Windows with cefpython and current (5.3.2) is installed on Linux with QT. However, of these two only the QT backend supports runtime icons, per [the pywebview documentation](https://pywebview.flowrl.com/examples/icon.html).

### Suggested Solution

Standardizing on the QT backend would allow for identical support on Windows, Mac, and Linux, with app icon support. QTPY is arguably better supported in general, as cefpython3 has not been updated in years.

### Alternatives

N/A - see [NiceGUI pull 634](https://github.com/zauberzeug/nicegui/pull/634)

### Additional Context

The [window] subinstall is broken on Ubuntu 22.04, as the unsupported pywebview 4.2 is installed in addition to current. If this feature request is not accepted, please update pyproject.toml line 76 to read:

`    "pywebview~=4.2" ; sys_platform == 'win32'",`

Separately, cefpython3 is [available for Mac on Python 3.10]( https://pypi.org/project/cefpython3-v66.1-for-python-3.10.2-unofficial/).

**Comment by mad-moo** [comment] 2024-11-13 19:55
Hey, thanks for this.

When we originally added webview we've tried the different backends. The chromium backend works by far the best and behaves similar to what you'd expect from a browser. With the others we've seen issues like videos not playing.

The reason we've ultimately decided on the current selection is because there were the best implementations on each platform that were actually reasonable to install. We'd often get error messages that webview couldn't find something even though it was installed on the system, or we plain couldn't find a package to get it to work on a platform.

We can review this - maybe the situation has changed. Your note on ubuntu also needs attention, thanks for pointing that out.

Ultimately _running well on a platform_ beats whether an icon can be displayed. Maybe we could also add an option to switch backents to `run_in_window`

**Comment by iwr-redmond** [comment] 2024-11-13 20:10
Take a look in  the code for the [QT backend](https://github.com/r0x0r/pywebview/blob/master/webview/platforms/qt.py), which has been updated recently for QT/Pyside6 (per [issue 1520](https://github.com/r0x0r/pywebview/issues/1520)). It uses qtwebengine, [i.e. Chromium](https://doc.qt.io/qt-6/qtwebenginewidgets-qtwebkitportingguide.html), rather than qtwebkit.

**Comment by mad-moo** [comment] 2024-11-13 20:12
Very good! That sounds promising. I'll try webview again on different platforms tomorrow

**Comment by mad-moo** [comment] 2024-11-14 14:28
Just a quick heads-up: `pywebview[qt]` looks promising indeed. Installs without problems on windows & linux. We'll shuffle around some code for Icon handling, and test on Mac. I'll keep you updated.

**Comment by mad-moo** [comment] 2024-11-14 18:23
Okay, sooo

1. The QT backend seems to be easy to install on Windows, Linux & Mac
2. It's _mostly_ functional, with e.g. Videos playing fine on Windows, but not Linux
3. Rendering is seriously broken. There are missing margins, the controls of the mediaplayer are stuck to the top of the component instead of the bottom, and bullet points in Markdown are positioned wrongly

Why the rendering in QT (using Chromium) is broken, when it works fine in Chrome, I don't know. The fix here is probably gonna be something like us working around the most serious issues, and updating `pywebview` when new releases drop, in the hope that it improves.

I've also looked at alternatives, like forgoing `pywebview` altogether and simply starting a locally installed browser without UI. To my surprise, neither Chrome nor Firefox seem to support this, despite other claims all over the internet. If anybody knows the correct magic combination of command line arguments for this, let me know.

This leads us to exactly where we were before - I think we should prefer CEF wherever it runs, and fall back to QT on other platforms. So CEF on Windows, and QT everywhere else.

I've also noticed that cefpython hasn't been updated in years - this is concerning, and another reason I hope QT improves, so we can switch to it globally in the future.

---

Ultimately this discussion started because of icons. The reason those don't show up in app mode isn't actually related to the backend though - we simply aren't setting it. We'll refactor the icon code to set the Icon on all platforms, so at least that part will be fixed soon.

**Comment by iwr-redmond** [comment] 2024-11-16 01:55
I've commented about the QT issues in #166.

As a backup plan, I've noticed that cefpython3 has [n-1 builds](https://pypi.org/project/cefpython3/66.0/#files) for all platforms. If QT doesn't work out as planned (hopefully I haven't gotten you burning daylight!) this could be a possible standard way forward. Cefpython3 [also supports a window icon](https://github.com/cztomczak/cefpython/blob/master/src/include/views/cef_window.h#200), although this feature is not yet enabled in pywebview.

**Comment by mad-moo** [comment] 2024-11-16 06:55
Thank you. I finally managed to force pywebview to use pyside. Not only do you have to install it, but also set an environment variable (`export QT_API=pyside6`). And indeed, this seems to resolve the issues!

I'll test this on Windows & Mac as well. Maybe we can indeed standardize on QT :crossed_fingers:

**Comment by mad-moo** [comment] 2024-11-16 06:59
Do you happen to know how to silence QT? The stdout spam is real

![image](https://github.com/user-attachments/assets/4a678367-8ffb-493a-9fe9-ecffb6073ed5)

**Comment by iwr-redmond** [comment] 2024-11-16 09:34
That's the GTK frontend attempting to start, not the QT one. 'gi' is the PyGObject module.

**Comment by mad-moo** [comment] 2024-11-16 09:38
Sorry, I was unclear. `gi` is Gtk, but everything below that is QT. All of the `gbm` messages, as well as the `js: ...` part. That's QT echoing the JS console to stdout.

Any idea how to suppress those?

**Comment by iwr-redmond** [comment] 2024-11-16 10:03
According to https://github.com/Almamu/linux-wallpaperengine/issues/217 and https://github.com/geany/geany-plugins/issues/1300 the messages you're seeing are GTK-related.

In any case, the QT code isn't honoring Pyside6.

venv-error:

```
pip install pywebview[qt]
pip install pyside6
python
import webview
webview.create_window('Pyside6 Missing', 'https://whatmyuseragent.com/')
webview.start(gui='qt')

```
Result shows QT5/webkit

venv-ok:

```
pip install pyside6 qtpy
pip install pywebview # no qt
python
import webview
webview.create_window('Pyside6 Expected', 'https://whatmyuseragent.com/')
webview.start(gui='qt')

```
Result shows QT6/webengine

**Comment by mad-moo** [comment] 2024-11-16 10:06
Trust me, it's QT :wink: 

```py
import PySide6
import qtpy

assert qtpy.PYSIDE6, "PySide6 must be the backend for webview"
```

I'll see what I can do

**Comment by mad-moo** [comment] 2024-11-17 17:48
We've confirmed `PySide6` works well on windows, linux & mac. We'll be switching to it in the next release

**Closed by mad-moo** 2024-11-17 17:48 UTC
Labels: good first issue, enhancement, needs discussion
