### ISSUE TITLE
[BUG]:  Javascript modules failing chrome, edge default mime type check

### ISSUE THREAD

**Issue by theodox** [rio-labs/rio#161] opened 2024-10-29 04:47 UTC
### Describe the bug

I installed rio (Windows 11, Python 311) and ran the setup using the tutorial.  I'm able to get a web page served using `rio run` however the page errors out with the following complaint:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

It looks like the same thing is happening if you create a tutorial app instead of a web page as well. 

### Steps to Reproduce

1. Install rio using Python 311 on Windows 11
2. Follow the tutorial on the website
3. Run the project, go to the served page on Chrome
4. Result: blank page, in console, strict MIME type checking error is visible

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome, Edge

### Browser version

Version 130.0.6723.70 (Official Build) (64-bit)

### What device are you using?

Desktop

**Comment by mad-moo** [comment] 2024-10-29 05:53
Thank you for reporting this. This happens when your operating system's MIME database is misconfigured and so doesn't recognize JavaScript/CSS files. The next release will contain a workaround.

Duplicate of #151

**Closed by mad-moo** 2024-10-29 05:53 UTC
Labels: bug
