### ISSUE TITLE
`proportions` in Container (`Rows` and `Columns`) do not work, if the component is added at a later stage

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#87] opened 2024-07-07 13:36 UTC
### Describe the bug

Container proportions for Rows and Columns are not functioning correctly. All the remaining space is left empty, and the children elements do not get the correct size (e.g., 1/3 of the available space), as demonstrated in the attached picture.

### Expected Behavior: 
Children should occupy the specified proportions of the available space (e.g., 1/3 each or homogeneous).

### Actual Behavior:
All remaining space is left empty, and children elements do not occupy the correct size.

### Steps to Reproduce

1. Create a container with Rows or Columns.
2. Set the `proportions="homogeneous"` parameter of e.g. `Row` for the child elements.
3. Observe the layout in the browser.

### Screenshots/Videos

<img width="528" alt="image" src="https://github.com/rio-labs/rio/assets/41641225/56eee2ed-844b-488a-bd33-51f431fa4b88">

### Operating System

Windows, MacOS, Linux

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari, Edge, Opera, Internet Explorer

**Comment by mad-moo** [comment] 2024-07-07 21:14
For anyone looking into this, they seem to work fine if the component is visible from the start. They _don't_ work, if the component is added at a later stage

**Comment by Sn3llius** [comment] 2024-07-08 12:46
Good point! It behaves the same on Safari.

**Comment by Aran-Fey** [comment] 2024-07-09 10:10
I'm not completely sure what the cause of this bug is, but I think ResizeObservers don't trigger on *every* change, which can lead to the calculated flex-grows being out-of-date. We've added a workaround with `requestAnimationFrame` that solves the issue in most cases, but there will almost certainly be cases where this bug still occurs.

**Comment by mad-moo** [comment] 2024-07-17 17:43
I'm closing this, since we haven't seen the issue pop up anymore. Feel free to re-open, should it emerge from the dead

**Closed by mad-moo** 2024-07-17 17:43 UTC
Labels: bug, layouting rework branch
